development:
  adapter: pg
  database: rackit_development
  username: rackit
  password:
  pool: 5
  timeout: 5000

test:
  adapter: pg
  database: rackit_test
  username: rackit
  password:
  pool: 5
  timeout: 5000

